config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'show/:id', to: 'users#show'
  root to: 'users#show'
  get 'show/:id', to: 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toxics, only: [:update, :show] do
    resources :withdraws, only: [:create]
  end

  resources :availabilities, only: [:index, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :missions, only: [:index]
  end
  resources :missions, only: [:new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :services, only: [:show, :edit, :update] do
    resources :messages, only: [:create, :destroy]
    resources :toxics, only: [:index]
    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:show, :create, :destroy] do
    resources :messages, only: :create
  end
  resources :missions, only: [:index]
  resources :scans, only: [:new, :create]
end

app/models/service.rb
class Service < ApplicationRecord
  has_many :users
  has_many :missions, dependent: :destroy
  has_many :bookings, through: :missions
  has_many :toxics, dependent: :destroy
  has_many :chatrooms, dependent: :destroy
  validates :name, :phone_number, :predominant_disease, :typical_workday, :predominant_drugs, presence: true
  after_create :create_chatroom


  def create_chatroom
    Chatroom.create(service: self, name: self.name)
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  def show
    @service = Service.find(params[:id])
  end

  def edit
    @service = Service.find(params[:id])
  end

  def update
    @service = Service.find(params[:id])
    @service.update(service_params)
    redirect_to service_path(@service)
  end

  private

  def service_params
    params.require(:service).permit(:name, :phone_number, :predominant_disease, :typical_workday, :predominant_drugs)
  end
end

app/views/services/edit.html.erb
<div class="container">
  <div class="description title my-3">
    <h1>Service <%= @service.name.capitalize %></h1>
  </div>
  <%= simple_form_for @service do |f| %>
    <%= f.input :phone_number, label: "Téléphone" %>
    <%= f.input :predominant_disease, label: "Pathologies prévalentes" %>
    <%= f.input :typical_workday, label: "Journée type" %>
    <%= f.input :predominant_drugs, label: "Médicaments prévalents" %>
    <%= f.submit "Actualiser", class: "btn btn-primary" %>
  <% end %>
</div>

app/views/services/show.html.erb
<div class="container">
      <div class="description title my-3">
        <h1>Service <%= @service.name.capitalize %></h1>
      </div>

    <div id="accordion" class="accordion">
    <%# div card Numéro Important  %>
        <div class="card mb-3" style="border-radius: 10px">
          <button class="card_service_day collapsed" data-toggle="collapse" data-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
          <h1>Numéros importants</h1>
          </button>
          <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordion">
            <div class="card-body">
             <% @service.phone_number.split(",").each_with_index do |line, i| %>
                  <% if i.even? %>
                    <p><strong><%= line %></strong></p>
                  <% else %>
                    <p><%= line %></p>
                  <% end %>
             <% end %>
            </div>
          </div>
        </div>

    <%# div card Journée type  %>
        <div class="card mb-3" style="border-radius: 10px">
          <button class="card_service_day collapsed" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          <h1> Journée type </h1>
          </button>
          <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordion">
            <div class="card-body">
              <%@service.typical_workday.split(",").each_with_index do |line, i|%>
                  <% if i.even? %>
                    <p><%= line %></p>
                  <% else %>
                    <p><%= line %></p>
                  <% end %>
             <% end %>
            </div>
          </div>
        </div>

    <%# div card Pathologies prévalentes  %>
        <div class="card mb-3" style="border-radius: 10px">
          <button class="card_service_day collapsed" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          <h1> Pathologies prévalentes</h1>
          </button>
          <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordion">
            <div class="card-body">
              <%= @service.predominant_disease %>
            </div>
          </div>
        </div>

    <%# div card Medicaments prévalents  %>
        <div class="card mb-3" style="border-radius: 10px">
          <button class="card_service_day collapsed" data-toggle="collapse" data-target="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          <h1> Médicaments prévalents</h1>
          </button>
          <div id="collapseFour" class="collapse" aria-labelledby="headingFour" data-parent="#accordion">
            <div class="card-body">
               <% @service.predominant_drugs.split(",").each_with_index do |line, i|%>
                  <% if i.even? %>
                    <p><%= line %></p>
                  <% else %>
                    <p><%= line %></p>
             <% end %>
            <% end %>
            </div>
          </div>
        </div>

  <div class="card mb-3">
    <%= link_to service_toxics_path(@service.id), class: "card_service_day box-shadow" do %>
        <h1>Gestion des Toxiques</h1>
    <% end %>
  </div>

  <% if current_user.admin == true %>
  <div class="card mb-3">
    <%= link_to edit_service_path(@service), class: "card_service_day" do %>
        <h1>Editer</h1>
    <% end %>
  </div>
  <% end %>
</div>
</div>