config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'show/:id', to: 'users#show'
  root to: 'users#show'
  get 'show/:id', to: 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toxics, only: [:update, :show] do
    resources :withdraws, only: [:create]
  end

  resources :availabilities, only: [:index, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :missions, only: [:index]
  end
  resources :missions, only: [:new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :services, only: [:show, :edit, :update] do
    resources :messages, only: [:create, :destroy]
    resources :toxics, only: [:index]
    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:show, :create, :destroy] do
    resources :messages, only: :create
  end
  resources :missions, only: [:index]
  resources :scans, only: [:new, :create]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :mission
  belongs_to :user
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    if current_user.admin == false
      # @bookings = Booking.where(user_id: current_user.id)
      # @bookings.each do |booking|
      #   @books << booking if booking.progress == "Validé"
      #   @books_futur << booking if booking.progress == "Venir"
      #   @books_passé << booking if booking.progress == "Passé"
      # end
      # return {
      #   now: @books,
      #   futur: @books_futur,
      #   past: @books_passé
      # }
      @bookings = []
      @books = Booking.where(user_id: current_user.id)
      @books.each do |booking|
        @bookings << booking if booking.progress == "Validé"
        if booking.progress == "Validé"
          booking.update(seen: true)
        end
      end
      return @bookings
    else
      @bookings = Booking.where(progress: "En attente")
    end

    return {
      now: @books,
      futur: @books_futur,
      past: @books_passé
    }

  end

  def create
    @booking = Booking.new(progress: "En attente")
    @booking.user = current_user
    @booking.mission = Mission.find(params[:mission_id])
    if @booking.save
      redirect_to root_path
    else
      redirect :back
    end
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    @booking.update(booking_params)
    redirect_to bookings_path
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to bookings_path
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_id, :progress, :user_id)
  end
end

app/views/bookings/edit.html.erb
<h1> Demande de missions</h1>
<div class="container">
<div class="image-container"><%= image_tag "mathilde.jpeg", class: "booking-avatar"%></div>
<div class="cards-booking">
  <p class="background-white"> Nom: <%= @booking.user.last_name %></p>
  <p class="background-white"> Prénom: <%= @booking.user.first_name %></p>
  <p class="background-white"> Expérience: <%= @booking.user.experience %></p>
  <p class="background-white"> Spécialité: <%= @booking.user.speciality %></p>
</div>

<div class="form-booking">
<%= simple_form_for @booking do |f| %>
  <%= f.input :progress, collection: ["Validé", "Refusé"], label: "Etat de la mission" %>
  <%= f.submit "Confirmer", class: "btn btn-primary" %>
<% end %>
</div>
</div>

app/views/bookings/index.html.erb
<%= image_tag "dispo.png", class:"img_bg"%>
<div class="container">
  <h3> Mes Missions</h3>
  <div class="booking">
  <% @bookings.each do |booking| %>
    <% if current_user.admin == false %>
      <%= link_to service_path(booking.mission.service), class: "blog-booking" do %>
        <div class="meta">
          <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg)"></div>
        </div>
        <div class="booking_card">
          <h1>Le <%= booking.mission.date %></h1>
          <h2> Service : <%= booking.mission.service.name %></h2>
        </div>
        <%= link_to booking_path(booking),
          method: :delete,
          data: { confirm: "Êtes-vous sûr ?" } do %>
          <i class="fas fa-trash" id="delete"></i>
          <% end %>
      <% end %>
    <% else %>
      <%= link_to edit_booking_path(booking), class: "blog-booking" do %>
        <div class="meta">
          <div class="photo" style="background-image: url(https://storage.googleapis.com/chydlx/codepen/blog-cards/image-1.jpg)"></div>
        </div>
        <div class="booking_card">
          <h1>Le <%= booking.mission.date %></h1>
          <h2> Service : <%= booking.mission.service.name %></h2>
        </div>
        <%= link_to booking_path(booking),
          method: :delete,
          data: { confirm: "Êtes-vous sûr ?" } do %>
          <i class="fas fa-trash" id="delete"></i>
          <% end %>
      <% end %>
    <% end %>
  <% end %>
  </div>

</div>