config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'show/:id', to: 'users#show'
  root to: 'users#show'
  get 'show/:id', to: 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toxics, only: [:update, :show] do
    resources :withdraws, only: [:create]
  end

  resources :availabilities, only: [:index, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :missions, only: [:index]
  end
  resources :missions, only: [:new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :services, only: [:show, :edit, :update] do
    resources :messages, only: [:create, :destroy]
    resources :toxics, only: [:index]
    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:show, :create, :destroy] do
    resources :messages, only: :create
  end
  resources :missions, only: [:index]
  resources :scans, only: [:new, :create]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  belongs_to :service
  has_many :availabilities, dependent: :destroy
  has_many :bookings, dependent: :destroy
  has_many :withdraws, dependent: :destroy
  has_many :last_messages, dependent: :destroy
  has_many :messages, dependent: :destroy
  has_many :chatrooms, through: :messages

  validates :phone_number, :first_name, :last_name, :experience, :speciality, presence: true

  def last_withdraw_for(toxic)
    withdraws.where(toxic_id: toxic).last
  end

  def pending_bookings_count
    self.service.bookings.where(progress: "En attente").count
  end

  def no_seen_bookings_count
    self.bookings.where(progress: "Validé", seen: nil).count
  end

  def message_notif?
    chatroom_ids = self.chatrooms.map(&:id)
    all_messages = Message.where(chatroom: chatroom_ids)
    last_message = LastMessage.where(user: self).last
    seen_messages = all_messages.where('created_at <= ?', last_message&.message&.created_at)
    seen_messages.count != all_messages.count
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]
  def show
    @user = current_user
  end
end

app/views/users/show.html.erb
<%= image_tag "accueil.png", class:"img_bg"%>
<div class="container" id="homepage">
  <% if current_user.admin == false %>
    <div class="blog-card">
      <i class="far fa-calendar-alt" id="logo"></i>
      <%= link_to "Mes disponibilités", availabilities_path,  class: "description"  %>
    </div>

    <div class="blog-card">
      <i class="fas fa-clipboard-list" id="logo"></i>
      <%= link_to "Mes Missions", bookings_path, class: "description" %>
    </div>

    <div class="blog-card">
      <i class="fas fa-clipboard-check" id="logo"></i>
      <%= link_to "Missions disponibles", missions_path, class: "description" %>
    </div>
  <% else %>
    <div class="blog-card">
      <i class="fas fa-calendar-plus" id="logo"></i>
      <%= link_to "Créer une mission", new_mission_path, class: "description" %>
    </div>

    <div class="blog-card">
      <i class="fas fa-clipboard-list" id="logo"></i>
      <%= link_to "Missions à valider", bookings_path, class: "description" %>
    </div>

    <div class="blog-card">
      <i class="fas fa-book-medical" id="logo"></i>
      <%= link_to "Mon service", service_path(current_user.service_id), class: "description" %>
    </div>
  <% end %>
</div>