config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'show/:id', to: 'users#show'
  root to: 'users#show'
  get 'show/:id', to: 'users#show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :toxics, only: [:update, :show] do
    resources :withdraws, only: [:create]
  end

  resources :availabilities, only: [:index, :new, :create, :destroy] do
    resources :bookings, only: [:new, :create]
    resources :missions, only: [:index]
  end
  resources :missions, only: [:new, :create] do
    resources :bookings, only: [:create]
  end
  resources :bookings, only: [:index, :edit, :update, :destroy]
  resources :services, only: [:show, :edit, :update] do
    resources :messages, only: [:create, :destroy]
    resources :toxics, only: [:index]
    resources :chatrooms, only: [:show, :create, :destroy] do
      resources :messages, only: :create
    end
  end
  resources :chatrooms, only: [:show, :create, :destroy] do
    resources :messages, only: :create
  end
  resources :missions, only: [:index]
  resources :scans, only: [:new, :create]
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <% if current_user&.admin == false %>
      <a href=<%= root_path %>><i class="fas fa-home"></i></a>
      <a href=<%= missions_path %>><i class="fas fa-book-medical"></i></a>

      <% if (user_signed_in?) && (current_user.bookings.present?) %>
        <a href=<%= service_chatroom_path(service_id: current_user.bookings.last.mission.service_id, id: current_user.bookings.last.mission.service.chatrooms.last.id) %>><i class="fas fa-comment-dots"></i></a>

      <% else %>
        <a class="wrapper-notif" href=<%= chatroom_path(current_user.service.chatrooms.last) %>><i class="fas fa-comment-dots"></i>
        <% if current_user.message_notif? %>
            <div class="notif d-flex justify-content-center align-items-center"><div>1</div></div>
        <% end %>
        </a>
      <% end %>

      <a href=<%= edit_user_registration_path %>><i class="fas fa-user-md"></i></a>
    <% else %>
      <a href=<%= root_path %>><i class="fas fa-home"></i></a>
      <a href=<%= bookings_path %>><i class="fas fa-clipboard-list"></i></a>

       <% if user_signed_in? %>
        <a href=<%= service_chatroom_path(service_id: current_user.service_id, id: current_user.service.chatrooms.last.id) %>><i class="fas fa-comment-dots"></i></a>
      <% else %>
        <a href=<%=  %>><i class="fas fa-comment-dots"></i></a>
      <% end %>
      <a href=<%= edit_user_registration_path %>><i class="fas fa-user-md"></i></a>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "logo.png", class: "navbar-logo"%>
    <% end %>
      <% if user_signed_in? %>
        <div class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="border-top-width: 0px; border-right-width: 0px; border-bottom-width: 0px; border-left-width: 0px;">
          <% if current_user.admin? %>
            <%= image_tag "florian.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% if !current_user.pending_bookings_count.zero? %>
            <div class=wrapper-notif><div class="notif"></div>
            <% end %>
          </div>
          <% else %>
            <%= image_tag "mathilde.jpeg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <% if !current_user.no_seen_bookings_count.zero? %>
            <div class=wrapper-notif><div class="notif"></div>
            <% end %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                  <%= link_to "Mon compte", edit_user_registration_path, class: "dropdown-item" %>
                  <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </div>
        </div>
      <% else %>
        <div class="nav-item">
          <%= link_to "Connection", new_user_session_path, class: "nav-link" %>
        </div>
      <% end %>
    </ul>
  </div>
</div>